### ISSUE TITLE
Where is the .existingIn method located?

### ISSUE THREAD

**Issue by lannzach** [nammedit/StateChanger#1]
Hi there. I'm getting the following error: `Message .existingIn not understood`. Is the `.existingIn` method something you wrote? Or is it from an earlier version of SC?

**Comment by nammedit** [comment]
Hey! It's an extension I made. I added stch_extensions.sc to the repository
with the .existingIn-method and also the .pseq-method if you didn't make it
yourself already.

**Comment by lannzach** [comment]
That seems to have fixed things, thanks!
